import { DynamicForm } from './models';
/*
export const mockup: DynamicForm = {
  postUrl: 'https://example.com/api/submitWizardForm',
  stepType: 2, //0 = wizard horizontal, 1= wizard vertical, 2= accordion, 3= tabs
  steps: [
    {
      title: 'Características físicas',
      containerConfig: {
        cssClass: '',
      },
      groups: [
        {
          groupName: '',
          groupConfig: {
            cssClass: '',
          },
          rows: [
            {
              fields: [
                {
                  name: 'weight',
                  label: 'Peso',
                  type: 'number',
                  value: null,
                  suffix: 'kg',
                  validators: ['required', 'minlength:2', 'maxlength:4'],
                  cssClass: 'col-md-3',
                },
                {
                  name: 'height',
                  label: 'Altura',
                  type: 'number',
                  value: null,
                  suffix: 'm',
                  validators: ['required', 'minLength:2', 'maxLength:2'],
                  cssClass: 'col-md-3',
                },
                {
                  name: 'imc',
                  label: 'IMC',
                  type: 'text',
                  value: '10',
                  validators: [],
                  cssClass: 'col-md-2',
                  disabled: true,
                },
                {
                  name: 'weist',
                  label: 'Circ. de cintura',
                  type: 'number',
                  value: null,
                  suffix: 'cm',
                  validators: ['minNumber:10', 'maxNumber:400'],
                  cssClass: 'col-md-4',
                },
                {
                  name: 'dynamic',
                  label: 'Circ. de cintura',
                  type: 'dynamic',
                  dynamicComponent: 'DrugsComponent',
                  value: [
                    { droga: 'asd', cantidad: 'asd', indicaciones: 'asd' },
                    { droga: 'zcx', cantidad: 'zxc', indicaciones: 'zcx' },
                  ],
                  cssClass: 'col-md-12',
                },
              ],
            },
          ],
        },
      ],
    },
    {
      title: 'Signos Vitales',
      containerConfig: {
        cssClass: '',
      },
      groups: [
        {
          groupName: '',
          groupConfig: {
            cssClass: '',
          },
          rows: [
            {
              fields: [
                {
                  name: 'bpMax',
                  label: 'TA Max',
                  type: 'number',
                  value: null,
                  suffix: 'mmHg',
                  validators: ['required', 'minNumber:1', 'maxNumber:300'],
                  cssClass: 'col-md-3',
                },
                {
                  name: 'bpMin',
                  label: 'TA Min',
                  type: 'number',
                  value: null,
                  suffix: 'mmHg',
                  validators: ['required', 'minNumber:1', 'maxNumber:300'],
                  cssClass: 'col-md-3',
                },
                {
                  name: 'temperature',
                  label: 'Temperatura',
                  type: 'number',
                  value: null,
                  suffix: 'º',
                  validators: ['required', 'minNumber:25', 'maxNumber:45'],
                  cssClass: 'col-md-3',
                },
                {
                  name: 'pulse',
                  label: 'Frecuencia cardíaca',
                  type: 'number',
                  value: null,
                  suffix: 'bpm',
                  validators: ['required', 'minNumber:25', 'maxNumber:200'],
                  cssClass: 'col-md-3',
                },
              ],
            },
            {
              fields: [
                {
                  name: 'breathing_frequency',
                  label: 'Frecuencia respiratoria',
                  type: 'number',
                  value: null,
                  suffix: 'bpm',
                  validators: ['required', 'minNumber:1', 'maxNumber:300'],
                  cssClass: 'col-md-3',
                },
                {
                  name: 'oxygen_saturation',
                  label: 'Saturación de oxígeno',
                  type: 'number',
                  value: null,
                  suffix: '%',
                  validators: ['required', 'minNumber:1', 'maxNumber:100'],
                  cssClass: 'col-md-3',
                },
              ],
            },
          ],
        },
      ],
    },
    {
      title: 'Anamnesis',
      containerConfig: {
        cssClass: '',
      },
      groups: [],
      subSteps: [
        {
          title: 'Diagnostico',
          containerConfig: {
            cssClass: '',
          },
          groups: [
            {
              groupName: '',
              groupConfig: {
                cssClass: '',
              },
              rows: [
                {
                  fields: [
                    {
                      name: 'diagnostic_dmt1',
                      label: 'DMT1',
                      type: 'checkbox',
                      value: null,
                      validators: [],
                      cssClass: 'col-md-3', // 50% width on medium and larger screens
                    },
                    {
                      name: 'diagnostic_dmt2',
                      label: 'DMT2',
                      type: 'checkbox',
                      value: null,
                      validators: [],
                      cssClass: 'col-md-3', // 50% width on medium and larger screens
                    },
                    {
                      name: 'diagnostic_gestational',
                      label: 'Gestacional',
                      type: 'checkbox',
                      value: null,
                      validators: [],
                      cssClass: 'col-md-3', // 50% width on medium and larger screens
                    },
                    {
                      name: 'diagnostic_other',
                      label: 'Otros',
                      type: 'checkbox',
                      value: null,
                      validators: [],
                      cssClass: 'col-md-3', // 50% width on medium and larger screens
                    },
                  ],
                },
                {
                  fields: [
                    {
                      name: 'diagnostic_age',
                      label: 'Edad al diagnóstico',
                      type: 'number',
                      value: null,
                      suffix: '',
                      validators: ['minNumber:1', 'maxNumber:120'],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'diagnostic_dmt_date',
                      label: 'Fecha diagnóstico DMT',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'diagnostic_observation',
                      label: 'Observaciones',
                      type: 'text',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-12',
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          title: 'Comorbilidades',
          containerConfig: {
            cssClass: '',
          },
          groups: [
            {
              groupName: '',
              groupConfig: {
                cssClass: '',
              },
              rows: [
                {
                  fields: [
                    {
                      name: 'comorbidity_hta',
                      label: 'HTA',
                      type: 'checkbox',
                      value: null,
                      validators: [],
                      cssClass: 'col-md-3', // 50% width on medium and larger screens
                    },
                    {
                      name: 'comorbidity_obesity',
                      label: 'Obesidad',
                      type: 'checkbox',
                      value: null,
                      validators: [],
                      cssClass: 'col-md-3', // 50% width on medium and larger screens
                    },
                    {
                      name: 'comorbidity_dyslipidemia',
                      label: 'Dislipemia',
                      type: 'checkbox',
                      value: null,
                      validators: [],
                      cssClass: 'col-md-3', // 50% width on medium and larger screens
                    },
                    {
                      name: 'comorbidity_smoking',
                      label: 'Tabaquismo',
                      type: 'checkbox',
                      value: null,
                      validators: [],
                      cssClass: 'col-md-3', // 50% width on medium and larger screens
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          title: 'Complicaciones',
          containerConfig: {
            cssClass: '',
          },
          groups: [
            {
              groupName: '',
              groupConfig: {
                cssClass: '',
              },
              rows: [
                {
                  fields: [
                    {
                      name: 'complications_hlv',
                      label: 'Hipert. Ventriculo Izq.',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'complications_ami',
                      label: 'Infarto Agudo Miocárdico',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'complications_stent',
                      label: 'Stent',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'complications_srm',
                      label: 'Cirug. Revas. Miocárdica',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'complications_hf',
                      label: 'Insuficiencia Cardiaca',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'complications_tis',
                      label: 'Acc. Isquémico Transitorio',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'complications_acv',
                      label: 'ACV',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'complications_pv',
                      label: 'Vasculopatía Periférica',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'complications_ick',
                      label: 'Insuf. Renal Crónica',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'complications_nephropathy',
                      label: 'Nefropatía',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'complications_dialysis',
                      label: 'Diálisis ',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'complications_txrenal',
                      label: 'TX Renal',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'complications_retinopathy',
                      label: 'Retinopatía ',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'complications_blindness',
                      label: 'Ceguera ',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'complications_neuropathies',
                      label: 'Neuropatias',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'complications_fu',
                      label: 'Ulcera de Pie',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'complications_df',
                      label: 'Pie Diabetico',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'complications_amputations',
                      label: 'Amputaciones',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'complications_hypoglycemia',
                      label: 'Hipoglucemias',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'complications_asthma',
                      label: 'Asma',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'complications_epoch',
                      label: 'EPOC',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'complications_hypothyroidism',
                      label: 'Hipotiroidismo',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'complications_other1',
                      label: 'Otros 1',
                      type: 'text',
                      value: null,
                      suffix: '',
                      tooltip: 'Especifique la complicación y cuándo sucedió.',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'complications_other2',
                      label: 'Otros 2',
                      type: 'text',
                      value: null,
                      suffix: '',
                      tooltip: 'Especifique la complicación y cuándo sucedió.',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          title: 'Controles',
          containerConfig: {
            cssClass: '',
          },
          groups: [
            {
              groupName: '',
              groupConfig: {
                cssClass: '',
              },
              rows: [
                {
                  fields: [
                    {
                      name: 'control_date',
                      label: 'Fecha',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'control_fbg',
                      label: 'Glucemia en ayunas',
                      type: 'number',
                      value: null,
                      suffix: '',
                      tooltip: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'control_hba1c',
                      label: 'HbA1C',
                      type: 'number',
                      value: null,
                      suffix: '',
                      tooltip: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'control_ldlc',
                      label: 'LDLc',
                      type: 'number',
                      value: null,
                      suffix: '',
                      tooltip: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'control_triglycerides',
                      label: 'Triglicéridos',
                      type: 'number',
                      value: null,
                      suffix: '',
                      tooltip: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'control_microalbuminuria ',
                      label: 'Microalbuminuria ',
                      type: 'number',
                      value: null,
                      suffix: '',
                      tooltip: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'control_sc',
                      label: 'Creatinina Sérica ',
                      type: 'number',
                      value: null,
                      suffix: '',
                      tooltip: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'control_cc',
                      label: 'Clearence de Creatinina',
                      type: 'number',
                      value: null,
                      suffix: '',
                      tooltip: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'control_sbp_dbp',
                      label: 'TA sistólica / TA diastólica',
                      type: 'text',
                      value: null,
                      suffix: '',
                      tooltip: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          title: 'Estudios complementarios',
          containerConfig: {
            cssClass: '',
          },
          groups: [
            {
              groupName: '',
              groupConfig: {
                cssClass: '',
              },
              rows: [
                {
                  fields: [
                    {
                      name: 'complementary_studies_1',
                      label: 'F. de ojo (Sin RD / RDNP / RDP)',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'complementary_studies_2',
                      label: 'E. de pie (Normal / Alterado)',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          title: 'Vigencia de la documentación',
          containerConfig: {
            cssClass: '',
          },
          groups: [
            {
              groupName: '',
              groupConfig: {
                cssClass: '',
              },
              rows: [
                {
                  fields: [
                    {
                      name: 'documentation_validity_date',
                      label: 'Fecha',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'documentation_validity_sn',
                      label: 'Obra social N° RNOS',
                      type: 'text',
                      value: null,
                      validators: [],
                      format: '',
                      cssClass: 'col-md-6',
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          title: 'Score estado',
          containerConfig: {
            cssClass: '',
          },
          groups: [
            {
              groupName: '',
              groupConfig: {
                cssClass: '',
              },
              rows: [
                {
                  fields: [
                    {
                      name: 'score_status_gh',
                      label: 'Hemoglobina Glicosilada',
                      type: 'text',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'score_status_bp',
                      label: 'Presión Arterial',
                      type: 'select',
                      value: null,
                      validators: [],
                      tooltip: 'Cantidad de medicación',
                      cssClass: 'col-md-6',
                      options: [
                        { value: '0', label: 'Ninguna' },
                        { value: '1', label: '1' },
                        { value: '2', label: '2' },
                        { value: '3', label: '3 o más' },
                      ],
                    },
                    {
                      name: 'score_status_creatinene',
                      label: 'Creatinina',
                      type: 'text',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'score_status_ldl',
                      label: 'LDL',
                      type: 'text',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'score_status_fundus',
                      label: 'Fondo de ojo',
                      type: 'select',
                      value: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      options: [
                        { value: '1', label: 'Sin Retinopatía' },
                        { value: '2', label: 'RNP' },
                        { value: '3', label: 'RP' },
                      ],
                    },
                    {
                      name: 'score_status_dq',
                      label: 'Cantidad de drogas',
                      type: 'select',
                      value: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      options: [
                        { value: '0', label: 'Ninguna' },
                        { value: '1', label: '1' },
                        { value: '2', label: '2-3' },
                        { value: '3', label: '4 o más' },
                      ],
                    },
                    {
                      name: 'score_status_pe',
                      label: 'Ejercicio Físico',
                      type: 'select',
                      value: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      options: [
                        { value: '0', label: 'Más de 3 veces por semana' },
                        { value: '1', label: '2 veces por semana' },
                        { value: '2', label: '1 vez por semana' },
                        { value: '3', label: 'Nunca' },
                      ],
                    },
                    {
                      name: 'score_status_nutrition',
                      label: 'Alimentación',
                      type: 'select',
                      value: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      options: [
                        { value: '0', label: 'Saludable' },
                        { value: '1', label: 'Regular' },
                        { value: '2', label: 'No saludable' },
                      ],
                    },
                    {
                      name: 'score_status_smoker',
                      label: 'Fumador',
                      type: 'select',
                      value: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      options: [
                        { value: '0', label: 'Si' },
                        { value: '1', label: 'No' },
                      ],
                    },
                    {
                      name: 'score_status_microalbuminuria ',
                      label: 'Microalbuminuria ',
                      type: 'text',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'score_status_ecv',
                      label: 'Evento CV',
                      type: 'select',
                      value: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      options: [
                        { value: '0', label: 'Si' },
                        { value: '1', label: 'No' },
                      ],
                    },
                    {
                      name: 'score_status_insulin',
                      label: 'Insulina',
                      type: 'select',
                      value: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      options: [
                        { value: '0', label: 'Si' },
                        { value: '1', label: 'No' },
                      ],
                    },
                    {
                      name: 'score_status_analogues',
                      label: 'Análogos',
                      type: 'select',
                      value: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      options: [
                        { value: '0', label: 'Si' },
                        { value: '1', label: 'No' },
                      ],
                    },
                    {
                      name: 'score_status_cm',
                      label: 'Cambio de medicación',
                      type: 'select',
                      value: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      options: [
                        { value: '0', label: 'Si' },
                        { value: '1', label: 'No' },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          title: 'Resumen de historia clínica',
          containerConfig: {
            cssClass: '',
          },
          groups: [
            {
              groupName: '',
              groupConfig: {
                cssClass: '',
              },
              rows: [
                {
                  fields: [
                    {
                      name: 'medical_summary_detail',
                      label: 'Detalle de cuadro clínico',
                      type: 'text',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'medical_summary_ps',
                      label: 'Esquema terapéutico previo',
                      type: 'text',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'medical_summary_enddate',
                      label: 'Fin tratamiento anterior',
                      type: 'date',
                      value: null,
                      tooltip:
                        'Si cambio de esquema, ingrese fecha de fin de tratamiento anterior',
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'medical_summary_reason',
                      label: 'Motivo de discontinuación',
                      type: 'text',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                    },
                    {
                      name: 'medical_summary_justification',
                      label: 'Justificación',
                      type: 'text',
                      value: null,
                      tooltip: 'Justificación médica del uso de la medicación',
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-12',
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          title: 'Tratamiento',
          containerConfig: {
            cssClass: '',
          },
          groups: [
            {
              groupName: '',
              groupConfig: {
                cssClass: '',
              },
              rows: [
                {
                  fields: [
                    {
                      name: 'treatment_hypolipe',
                      label: 'Hipolemiante',
                      type: 'select',
                      value: null,
                      tooltip: 'Tratamiento hipolemiante (estatinas u otros)',
                      validators: [],
                      cssClass: 'col-md-6',
                      options: [
                        { value: '0', label: 'Si' },
                        { value: '1', label: 'No' },
                      ],
                    },
                    {
                      name: 'treatment_antihypertensive',
                      label: 'Antihipertensivo',
                      type: 'select',
                      value: null,
                      tooltip: 'Tratamiento Antihipertensivo',
                      validators: [],
                      cssClass: 'col-md-6',
                      options: [
                        { value: '0', label: 'Si' },
                        { value: '1', label: 'No' },
                      ],
                    },
                    {
                      name: 'treatment_antiaggregation',
                      label: 'Antiagregación',
                      type: 'select',
                      value: null,
                      tooltip: 'Tratamiento Antiagregación',
                      validators: [],
                      cssClass: 'col-md-6',
                      options: [
                        { value: '0', label: 'Si' },
                        { value: '1', label: 'No' },
                      ],
                    },
                    {
                      name: 'treatment_gsm',
                      label: 'Automonitoreo glucémico',
                      type: 'select',
                      value: null,
                      tooltip: 'Tratamiento Automonitoreo glucémico',
                      validators: [],
                      cssClass: 'col-md-6',
                      options: [
                        { value: '0', label: 'Si' },
                        { value: '1', label: 'No' },
                      ],
                    },
                    {
                      name: 'treatment_pa',
                      label: 'Actividad física',
                      type: 'select',
                      value: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      options: [
                        { value: '0', label: 'Si' },
                        { value: '1', label: 'No' },
                      ],
                    },
                    {
                      name: 'treatment_ip',
                      label: 'Bomba de insulina',
                      type: 'select',
                      value: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      options: [
                        { value: '0', label: 'Si' },
                        { value: '1', label: 'No' },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
*/

export const mockup: DynamicForm = {
  postUrl: 'https://example.com/api/submitWizardForm',
  stepType: 2,
  postId: '1',
  formHeader: 'Anamnesis',
  formSubmitButton: 'Guardar',
  steps: [
    {
      title: 'Características físicas',
      containerConfig: {
        cssClass: '',
      },
      groups: [
        {
          groupName: '',
          groupConfig: {
            cssClass: '',
          },
          rows: [
            {
              fields: [
                {
                  name: 'weight',
                  label: 'Peso',
                  type: 'number',
                  value: 12,
                  suffix: 'kg',
                  validators: ['required', 'minlength:2', 'maxlength:4'],
                  cssClass: 'col-md-3',
                  disabled: null,
                  apiUrl: null,
                  dependsOn: null,
                  queryParam: null,
                  format: null,
                  tooltip: null,
                  options: null,
                },
                {
                  name: 'height',
                  label: 'Altura',
                  type: 'number',
                  value: 12,
                  suffix: 'm',
                  validators: ['required', 'minLength:2', 'maxLength:2'],
                  cssClass: 'col-md-3',
                  disabled: null,
                  apiUrl: null,
                  dependsOn: null,
                  queryParam: null,
                  format: null,
                  tooltip: null,
                  options: null,
                },
                {
                  name: 'imc',
                  label: 'IMC',
                  type: 'text',
                  value: '10',
                  suffix: null,
                  validators: [],
                  cssClass: 'col-md-2',
                  disabled: true,
                  apiUrl: null,
                  dependsOn: null,
                  queryParam: null,
                  format: null,
                  tooltip: null,
                  options: null,
                },
                {
                  name: 'weist',
                  label: 'Circ. de cintura',
                  type: 'number',
                  value: 12,
                  suffix: 'cm',
                  validators: ['minNumber:10', 'maxNumber:400'],
                  cssClass: 'col-md-4',
                  disabled: null,
                  apiUrl: null,
                  dependsOn: null,
                  queryParam: null,
                  format: null,
                  tooltip: null,
                  options: null,
                },
                {
                  name: 'dynamic',
                  label: 'Circ. de cintura',
                  type: 'dynamic',
                  value: [
                    {
                      droga: 'asd',
                      cantidad: 'asd',
                      indicaciones: 'asd',
                    },
                    {
                      droga: 'zcx',
                      cantidad: 'zxc',
                      indicaciones: 'zcx',
                    },
                  ],
                  suffix: null,
                  dynamicComponent: 'DrugsComponent',
                  validators: null,
                  cssClass: 'col-md-12',
                  disabled: null,
                  apiUrl: null,
                  dependsOn: null,
                  queryParam: null,
                  format: null,
                  tooltip: null,
                  options: null,
                },
                {
                  name: 'dynamic2',
                  label: 'Circ. de cintura',
                  type: 'dynamic',
                  value: [
                    {
                      droga: 'asd',
                      cantidad: 'asd',
                      indicaciones: 'asd',
                    },
                    {
                      droga: 'zcx',
                      cantidad: 'zxc',
                      indicaciones: 'zcx',
                    },
                  ],
                  suffix: null,
                  dynamicComponent: 'DrugsComponent',
                  validators: null,
                  cssClass: 'col-md-12',
                  disabled: null,
                  apiUrl: null,
                  dependsOn: null,
                  queryParam: null,
                  format: null,
                  tooltip: null,
                  options: null,
                },
              ],
            },
          ],
        },
      ],
      subSteps: [],
    },
    {
      title: 'Signos Vitales',
      containerConfig: {
        cssClass: '',
      },
      groups: [
        {
          groupName: '',
          groupConfig: {
            cssClass: '',
          },
          rows: [
            {
              fields: [
                {
                  name: 'bpMax',
                  label: 'TA Max',
                  type: 'number',
                  value: 12,
                  suffix: 'mmHg',
                  validators: ['required', 'minNumber:1', 'maxNumber:300'],
                  cssClass: 'col-md-3',
                  disabled: null,
                  apiUrl: null,
                  dependsOn: null,
                  queryParam: null,
                  format: null,
                  tooltip: null,
                  options: null,
                },
                {
                  name: 'bpMin',
                  label: 'TA Min',
                  type: 'number',
                  value: 12,
                  suffix: 'mmHg',
                  validators: ['required', 'minNumber:1', 'maxNumber:300'],
                  cssClass: 'col-md-3',
                  disabled: null,
                  apiUrl: null,
                  dependsOn: null,
                  queryParam: null,
                  format: null,
                  tooltip: null,
                  options: null,
                },
                {
                  name: 'temperature',
                  label: 'Temperatura',
                  type: 'number',
                  value: 26,
                  suffix: 'º',
                  validators: ['required', 'minNumber:25', 'maxNumber:45'],
                  cssClass: 'col-md-3',
                  disabled: null,
                  apiUrl: null,
                  dependsOn: null,
                  queryParam: null,
                  format: null,
                  tooltip: null,
                  options: null,
                },
                {
                  name: 'pulse',
                  label: 'Frecuencia cardíaca',
                  type: 'number',
                  value: 33,
                  suffix: 'bpm',
                  validators: ['required', 'minNumber:25', 'maxNumber:200'],
                  cssClass: 'col-md-3',
                  disabled: null,
                  apiUrl: null,
                  dependsOn: null,
                  queryParam: null,
                  format: null,
                  tooltip: null,
                  options: null,
                },
              ],
            },
            {
              fields: [
                {
                  name: 'breathing_frequency',
                  label: 'Frecuencia respiratoria',
                  type: 'number',
                  value: 33,
                  suffix: 'bpm',
                  validators: ['required', 'minNumber:1', 'maxNumber:300'],
                  cssClass: 'col-md-3',
                  disabled: null,
                  apiUrl: null,
                  dependsOn: null,
                  queryParam: null,
                  format: null,
                  tooltip: null,
                  options: null,
                },
                {
                  name: 'oxygen_saturation',
                  label: 'Saturación de oxígeno',
                  type: 'number',
                  value: 33,
                  suffix: '%',
                  validators: ['required', 'minNumber:1', 'maxNumber:100'],
                  cssClass: 'col-md-3',
                  disabled: null,
                  apiUrl: null,
                  dependsOn: null,
                  queryParam: null,
                  format: null,
                  tooltip: null,
                  options: null,
                },
              ],
            },
          ],
        },
      ],
      subSteps: [],
    },
    {
      title: 'Anamnesis',
      containerConfig: {
        cssClass: '',
      },
      groups: [],
      subSteps: [
        {
          title: 'Diagnostico',
          containerConfig: {
            cssClass: '',
          },
          groups: [
            {
              groupName: '',
              groupConfig: {
                cssClass: '',
              },
              rows: [
                {
                  fields: [
                    {
                      name: 'diagnostic_dmt1',
                      label: 'DMT1',
                      type: 'checkbox',
                      value: true,
                      suffix: null,
                      validators: [],
                      cssClass: 'col-md-3',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'diagnostic_dmt2',
                      label: 'DMT2',
                      type: 'checkbox',
                      value: true,
                      suffix: null,
                      validators: [],
                      cssClass: 'col-md-3',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'diagnostic_gestational',
                      label: 'Gestacional',
                      type: 'checkbox',
                      value: '',
                      suffix: null,
                      validators: [],
                      cssClass: 'col-md-3',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'diagnostic_other',
                      label: 'Otros',
                      type: 'checkbox',
                      value: '',
                      suffix: null,
                      validators: [],
                      cssClass: 'col-md-3',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                  ],
                },
                {
                  fields: [
                    {
                      name: 'diagnostic_age',
                      label: 'Edad al diagnóstico',
                      type: 'number',
                      value: 33,
                      suffix: '',
                      validators: ['minNumber:1', 'maxNumber:120'],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'diagnostic_dmt_date',
                      label: 'Fecha diagnóstico DMT',
                      type: 'date',
                      value: '2024-09-02T00:00:00.000Z',
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'diagnostic_observation',
                      label: 'Observaciones',
                      type: 'text',
                      value: 'asd',
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-12',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                  ],
                },
              ],
            },
          ],
          subSteps: null,
        },
        {
          title: 'Comorbilidades',
          containerConfig: {
            cssClass: '',
          },
          groups: [
            {
              groupName: '',
              groupConfig: {
                cssClass: '',
              },
              rows: [
                {
                  fields: [
                    {
                      name: 'comorbidity_hta',
                      label: 'HTA',
                      type: 'checkbox',
                      value: true,
                      suffix: null,
                      validators: [],
                      cssClass: 'col-md-3',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'comorbidity_obesity',
                      label: 'Obesidad',
                      type: 'checkbox',
                      value: true,
                      suffix: null,
                      validators: [],
                      cssClass: 'col-md-3',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'comorbidity_dyslipidemia',
                      label: 'Dislipemia',
                      type: 'checkbox',
                      value: true,
                      suffix: null,
                      validators: [],
                      cssClass: 'col-md-3',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'comorbidity_smoking',
                      label: 'Tabaquismo',
                      type: 'checkbox',
                      value: true,
                      suffix: null,
                      validators: [],
                      cssClass: 'col-md-3',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                  ],
                },
              ],
            },
          ],
          subSteps: null,
        },
        {
          title: 'Complicaciones',
          containerConfig: {
            cssClass: '',
          },
          groups: [
            {
              groupName: '',
              groupConfig: {
                cssClass: '',
              },
              rows: [
                {
                  fields: [
                    {
                      name: 'complications_hlv',
                      label: 'Hipert. Ventriculo Izq.',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'complications_ami',
                      label: 'Infarto Agudo Miocárdico',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'complications_stent',
                      label: 'Stent',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'complications_srm',
                      label: 'Cirug. Revas. Miocárdica',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'complications_hf',
                      label: 'Insuficiencia Cardiaca',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'complications_tis',
                      label: 'Acc. Isquémico Transitorio',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'complications_acv',
                      label: 'ACV',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'complications_pv',
                      label: 'Vasculopatía Periférica',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'complications_ick',
                      label: 'Insuf. Renal Crónica',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'complications_nephropathy',
                      label: 'Nefropatía',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'complications_dialysis',
                      label: 'Diálisis ',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'complications_txrenal',
                      label: 'TX Renal',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'complications_retinopathy',
                      label: 'Retinopatía ',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'complications_blindness',
                      label: 'Ceguera ',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'complications_neuropathies',
                      label: 'Neuropatias',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'complications_fu',
                      label: 'Ulcera de Pie',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'complications_df',
                      label: 'Pie Diabetico',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'complications_amputations',
                      label: 'Amputaciones',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'complications_hypoglycemia',
                      label: 'Hipoglucemias',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'complications_asthma',
                      label: 'Asma',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'complications_epoch',
                      label: 'EPOC',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'complications_hypothyroidism',
                      label: 'Hipotiroidismo',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'complications_other1',
                      label: 'Otros 1',
                      type: 'text',
                      value: 'asd',
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: 'Especifique la complicación y cuándo sucedió.',
                      options: null,
                    },
                    {
                      name: 'complications_other2',
                      label: 'Otros 2',
                      type: 'text',
                      value: '',
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: 'Especifique la complicación y cuándo sucedió.',
                      options: null,
                    },
                  ],
                },
              ],
            },
          ],
          subSteps: null,
        },
        {
          title: 'Controles',
          containerConfig: {
            cssClass: '',
          },
          groups: [
            {
              groupName: '',
              groupConfig: {
                cssClass: '',
              },
              rows: [
                {
                  fields: [
                    {
                      name: 'control_date',
                      label: 'Fecha',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'control_fbg',
                      label: 'Glucemia en ayunas',
                      type: 'number',
                      value: 33,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: '',
                      options: null,
                    },
                    {
                      name: 'control_hba1c',
                      label: 'HbA1C',
                      type: 'number',
                      value: 33,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: '',
                      options: null,
                    },
                    {
                      name: 'control_ldlc',
                      label: 'LDLc',
                      type: 'number',
                      value: '',
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: '',
                      options: null,
                    },
                    {
                      name: 'control_triglycerides',
                      label: 'Triglicéridos',
                      type: 'number',
                      value: '',
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: '',
                      options: null,
                    },
                    {
                      name: 'control_microalbuminuria ',
                      label: 'Microalbuminuria ',
                      type: 'number',
                      value: '',
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: '',
                      options: null,
                    },
                    {
                      name: 'control_sc',
                      label: 'Creatinina Sérica ',
                      type: 'number',
                      value: '',
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: '',
                      options: null,
                    },
                    {
                      name: 'control_cc',
                      label: 'Clearence de Creatinina',
                      type: 'number',
                      value: '',
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: '',
                      options: null,
                    },
                    {
                      name: 'control_sbp_dbp',
                      label: 'TA sistólica / TA diastólica',
                      type: 'text',
                      value: '',
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: '',
                      options: null,
                    },
                  ],
                },
              ],
            },
          ],
          subSteps: null,
        },
        {
          title: 'Estudios complementarios',
          containerConfig: {
            cssClass: '',
          },
          groups: [
            {
              groupName: '',
              groupConfig: {
                cssClass: '',
              },
              rows: [
                {
                  fields: [
                    {
                      name: 'complementary_studies_1',
                      label: 'F. de ojo (Sin RD / RDNP / RDP)',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'complementary_studies_2',
                      label: 'E. de pie (Normal / Alterado)',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                  ],
                },
              ],
            },
          ],
          subSteps: null,
        },
        {
          title: 'Vigencia de la documentación',
          containerConfig: {
            cssClass: '',
          },
          groups: [
            {
              groupName: '',
              groupConfig: {
                cssClass: '',
              },
              rows: [
                {
                  fields: [
                    {
                      name: 'documentation_validity_date',
                      label: 'Fecha',
                      type: 'date',
                      value: '2024-09-13T00:00:00.000Z',
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'documentation_validity_sn',
                      label: 'Obra social N° RNOS',
                      type: 'text',
                      value: '',
                      suffix: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: '',
                      tooltip: null,
                      options: null,
                    },
                  ],
                },
              ],
            },
          ],
          subSteps: null,
        },
        {
          title: 'Score estado',
          containerConfig: {
            cssClass: '',
          },
          groups: [
            {
              groupName: '',
              groupConfig: {
                cssClass: '',
              },
              rows: [
                {
                  fields: [
                    {
                      name: 'score_status_gh',
                      label: 'Hemoglobina Glicosilada',
                      type: 'text',
                      value: '',
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'score_status_bp',
                      label: 'Presión Arterial',
                      type: 'select',
                      value: '',
                      suffix: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: 'Cantidad de medicación',
                      options: [
                        {
                          value: '0',
                          label: 'Ninguna',
                        },
                        {
                          value: '1',
                          label: '1',
                        },
                        {
                          value: '2',
                          label: '2',
                        },
                        {
                          value: '3',
                          label: '3 o más',
                        },
                      ],
                    },
                    {
                      name: 'score_status_creatinene',
                      label: 'Creatinina',
                      type: 'text',
                      value: 'asddasdas',
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'score_status_ldl',
                      label: 'LDL',
                      type: 'text',
                      value: '',
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'score_status_fundus',
                      label: 'Fondo de ojo',
                      type: 'select',
                      value: '2',
                      suffix: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: [
                        {
                          value: '1',
                          label: 'Sin Retinopatía',
                        },
                        {
                          value: '2',
                          label: 'RNP',
                        },
                        {
                          value: '3',
                          label: 'RP',
                        },
                      ],
                    },
                    {
                      name: 'score_status_dq',
                      label: 'Cantidad de drogas',
                      type: 'select',
                      value: '',
                      suffix: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: [
                        {
                          value: '0',
                          label: 'Ninguna',
                        },
                        {
                          value: '1',
                          label: '1',
                        },
                        {
                          value: '2',
                          label: '2-3',
                        },
                        {
                          value: '3',
                          label: '4 o más',
                        },
                      ],
                    },
                    {
                      name: 'score_status_pe',
                      label: 'Ejercicio Físico',
                      type: 'select',
                      value: '',
                      suffix: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: [
                        {
                          value: '0',
                          label: 'Más de 3 veces por semana',
                        },
                        {
                          value: '1',
                          label: '2 veces por semana',
                        },
                        {
                          value: '2',
                          label: '1 vez por semana',
                        },
                        {
                          value: '3',
                          label: 'Nunca',
                        },
                      ],
                    },
                    {
                      name: 'score_status_nutrition',
                      label: 'Alimentación',
                      type: 'select',
                      value: '',
                      suffix: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: [
                        {
                          value: '0',
                          label: 'Saludable',
                        },
                        {
                          value: '1',
                          label: 'Regular',
                        },
                        {
                          value: '2',
                          label: 'No saludable',
                        },
                      ],
                    },
                    {
                      name: 'score_status_smoker',
                      label: 'Fumador',
                      type: 'select',
                      value: '',
                      suffix: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: [
                        {
                          value: '0',
                          label: 'Si',
                        },
                        {
                          value: '1',
                          label: 'No',
                        },
                      ],
                    },
                    {
                      name: 'score_status_microalbuminuria ',
                      label: 'Microalbuminuria ',
                      type: 'text',
                      value: '',
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'score_status_ecv',
                      label: 'Evento CV',
                      type: 'select',
                      value: '',
                      suffix: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: [
                        {
                          value: '0',
                          label: 'Si',
                        },
                        {
                          value: '1',
                          label: 'No',
                        },
                      ],
                    },
                    {
                      name: 'score_status_insulin',
                      label: 'Insulina',
                      type: 'select',
                      value: '',
                      suffix: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: [
                        {
                          value: '0',
                          label: 'Si',
                        },
                        {
                          value: '1',
                          label: 'No',
                        },
                      ],
                    },
                    {
                      name: 'score_status_analogues',
                      label: 'Análogos',
                      type: 'select',
                      value: '',
                      suffix: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: [
                        {
                          value: '0',
                          label: 'Si',
                        },
                        {
                          value: '1',
                          label: 'No',
                        },
                      ],
                    },
                    {
                      name: 'score_status_cm',
                      label: 'Cambio de medicación',
                      type: 'select',
                      value: '',
                      suffix: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: [
                        {
                          value: '0',
                          label: 'Si',
                        },
                        {
                          value: '1',
                          label: 'No',
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
          subSteps: null,
        },
        {
          title: 'Resumen de historia clínica',
          containerConfig: {
            cssClass: '',
          },
          groups: [
            {
              groupName: '',
              groupConfig: {
                cssClass: '',
              },
              rows: [
                {
                  fields: [
                    {
                      name: 'medical_summary_detail',
                      label: 'Detalle de cuadro clínico',
                      type: 'text',
                      value: '',
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'medical_summary_ps',
                      label: 'Esquema terapéutico previo',
                      type: 'text',
                      value: '',
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'medical_summary_enddate',
                      label: 'Fin tratamiento anterior',
                      type: 'date',
                      value: null,
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip:
                        'Si cambio de esquema, ingrese fecha de fin de tratamiento anterior',
                      options: null,
                    },
                    {
                      name: 'medical_summary_reason',
                      label: 'Motivo de discontinuación',
                      type: 'text',
                      value: '',
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: null,
                    },
                    {
                      name: 'medical_summary_justification',
                      label: 'Justificación',
                      type: 'text',
                      value: '',
                      suffix: '',
                      validators: [],
                      cssClass: 'col-md-12',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: 'Justificación médica del uso de la medicación',
                      options: null,
                    },
                  ],
                },
              ],
            },
          ],
          subSteps: null,
        },
        {
          title: 'Tratamiento',
          containerConfig: {
            cssClass: '',
          },
          groups: [
            {
              groupName: '',
              groupConfig: {
                cssClass: '',
              },
              rows: [
                {
                  fields: [
                    {
                      name: 'treatment_hypolipe',
                      label: 'Hipolemiante',
                      type: 'select',
                      value: '',
                      suffix: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: 'Tratamiento hipolemiante (estatinas u otros)',
                      options: [
                        {
                          value: '0',
                          label: 'Si',
                        },
                        {
                          value: '1',
                          label: 'No',
                        },
                      ],
                    },
                    {
                      name: 'treatment_antihypertensive',
                      label: 'Antihipertensivo',
                      type: 'select',
                      value: '',
                      suffix: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: 'Tratamiento Antihipertensivo',
                      options: [
                        {
                          value: '0',
                          label: 'Si',
                        },
                        {
                          value: '1',
                          label: 'No',
                        },
                      ],
                    },
                    {
                      name: 'treatment_antiaggregation',
                      label: 'Antiagregación',
                      type: 'select',
                      value: '',
                      suffix: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: 'Tratamiento Antiagregación',
                      options: [
                        {
                          value: '0',
                          label: 'Si',
                        },
                        {
                          value: '1',
                          label: 'No',
                        },
                      ],
                    },
                    {
                      name: 'treatment_gsm',
                      label: 'Automonitoreo glucémico',
                      type: 'select',
                      value: '',
                      suffix: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: 'Tratamiento Automonitoreo glucémico',
                      options: [
                        {
                          value: '0',
                          label: 'Si',
                        },
                        {
                          value: '1',
                          label: 'No',
                        },
                      ],
                    },
                    {
                      name: 'treatment_pa',
                      label: 'Actividad física',
                      type: 'select',
                      value: '',
                      suffix: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: [
                        {
                          value: '0',
                          label: 'Si',
                        },
                        {
                          value: '1',
                          label: 'No',
                        },
                      ],
                    },
                    {
                      name: 'treatment_ip',
                      label: 'Bomba de insulina',
                      type: 'select',
                      value: '',
                      suffix: null,
                      validators: [],
                      cssClass: 'col-md-6',
                      disabled: null,
                      apiUrl: null,
                      dependsOn: null,
                      queryParam: null,
                      format: null,
                      tooltip: null,
                      options: [
                        {
                          value: '0',
                          label: 'Si',
                        },
                        {
                          value: '1',
                          label: 'No',
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
          subSteps: null,
        },
      ],
    },
  ],
};
