export enum WellKnownWorkflowTypes {
    Claim = 1,
    TreatmentRequest = 2,
    PurchaseOrder = 3,
    InvoiceApproval = 4,
    Project = 5,
    FeedbackTicket = 6,
    LoanApproval = 7,
    LeadApproval = 8,
    InventoryDispatch = 9,
    InventoryReceipt = 10,
    CuponStarByClubRedondoBenefit = 11,
    OwnBenefitCR = 12,
    PurchaseProducts = 13,
    CuponStar = 14,
    Tourism = 15,
    OwnBenefit = 16,
    EcommercePurchaseOrder = 17,
    EcommercePurchaseOrderCash = 18,
    LoanStoreRequest = 19,
    EcommercePurchaseOrderCheckingAccount = 20,
    HealthManagementChangeEmployer = 24,
    HealthManagementNewEmployer = 25,
    HealthManagementRemoveEmployer = 26,
    HealthInvoice = 27
}
